name: Build, Sign, and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write
  actions: read

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Syft and Cosign
        shell: bash
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          curl -sSfL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o /usr/local/bin/cosign
          chmod +x /usr/local/bin/cosign
          syft version
          cosign version

      - name: Build artifact (zip)
        run: |
          make build
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Generate SBOM (Syft)
        run: |
          make sbom || (echo "Falling back to direct syft" && syft dir:src -o spdx-json > dist/sbom.spdx.json)

      - name: Upload artifact to workflow run
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ github.ref_name }}
          path: |
            dist/*.zip
            dist/sbom.spdx.json

      - name: Keyless sign artifact with Cosign
        run: |
          ART=$(ls dist/*.zip | head -n1)
          cosign sign-blob --yes --oidc-provider=github "$ART" \
            --output-signature "$ART.sig" \
            --output-certificate "$ART.cert"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/*.zip
            dist/*.zip.sig
            dist/*.zip.cert
            dist/sbom.spdx.json

